### ISSUE TITLE
Failure in mergeLibDexDebug task when upgrading from 2.1.5 to 3.1.3

### ISSUE THREAD

**Issue by mshafrir-stripe** [getsentry/sentry-android-gradle-plugin#360]
### Gradle Version

7.5

### AGP Version

7.2.1

### Code Minifier/Optimizer

R8

### Version

3.1.3

### Sentry SDK Version

5.7.4

### Steps to Reproduce

1. Upgrade `io.sentry.android.gradle` from `2.1.5` to `3.1.3`
2. Run `./gradlew build`

### Expected Result

Complete successfully

### Actual Result

```
00:09:49.145	[sentry] Error while instrumenting r.a (Ljava/lang/String;)V.
00:09:49.145	Please report this issue at https://github.com/getsentry/sentry-android-gradle-plugin/issues
00:09:49.147	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
00:09:49.147		at org.objectweb.asm.Frame.merge(Frame.java:1268)
00:09:49.147		at org.objectweb.asm.Frame.merge(Frame.java:1233)
00:09:49.147		at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
00:09:49.147		at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
00:09:49.147		at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
00:09:49.147		at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(LocalVariablesSorter.java:148)
00:09:49.147		at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
00:09:49.147		at io.sentry.android.gradle.instrumentation.util.CatchingMethodVisitor.visitMaxs(CatchingMethodVisitor.kt:24)
00:09:49.147		at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
00:09:49.147		at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
00:09:49.147		at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
00:09:49.147		at io.sentry.android.gradle.instrumentation.util.AnalyzingVisitor.visitEnd(AnalyzingVisitor.kt:14)
00:09:49.147		at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
00:09:49.147		at org.objectweb.asm.ClassReader.accept(ClassReader.java:725)
00:09:49.147		at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
00:09:49.147		at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentByteCode(AsmInstrumentationManager.kt:223)
00:09:49.147		at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentClass(AsmInstrumentationManager.kt:255)
00:09:49.147		at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassToJar(AsmInstrumentationManager.kt:342)
00:09:49.147		at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassesFromJarToJar(AsmInstrumentationManager.kt:157)
00:09:49.147		at com.android.build.gradle.internal.dependency.AsmClassesTransform.transform(AsmClassesTransform.kt:140)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformer.transform(DefaultTransformer.java:264)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$AbstractTransformerExecution$1.call(DefaultTransformerInvocationFactory.java:296)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$AbstractTransformerExecution$1.call(DefaultTransformerInvocationFactory.java:291)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$AbstractTransformerExecution.execute(DefaultTransformerInvocationFactory.java:291)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
00:09:49.147		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
00:09:49.147		at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
00:09:49.147		at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
00:09:49.147		at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
00:09:49.147		at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
00:09:49.147		at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
00:09:49.147		at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
00:09:49.147		at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
00:09:49.147		at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:61)
00:09:49.147		at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:42)
00:09:49.147		at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
00:09:49.147		at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:180)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.executeAndStoreInCache(BuildCacheStep.java:155)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$4(BuildCacheStep.java:125)
00:09:49.147		at java.base/java.util.Optional.orElseGet(Optional.java:369)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$5(BuildCacheStep.java:125)
00:09:49.147		at org.gradle.internal.Try$Success.map(Try.java:164)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.executeWithCache(BuildCacheStep.java:85)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$0(BuildCacheStep.java:74)
00:09:49.147		at org.gradle.internal.Either$Left.fold(Either.java:115)
00:09:49.147		at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
00:09:49.147		at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
00:09:49.147		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
00:09:49.147		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
00:09:49.147		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
00:09:49.147		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
00:09:49.147		at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
00:09:49.147		at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
00:09:49.147		at java.base/java.util.Optional.orElseGet(Optional.java:369)
00:09:49.147		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
00:09:49.147		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
00:09:49.147		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
00:09:49.147		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
00:09:49.147		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
00:09:49.147		at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)
00:09:49.147		at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
00:09:49.147		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
00:09:49.147		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
00:09:49.147		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)
00:09:49.147		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
00:09:49.147		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)
00:09:49.147		at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
00:09:49.147		at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
00:09:49.147		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
00:09:49.147		at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
00:09:49.147		at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
00:09:49.147		at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.MutableTransformationWorkspaceServices$MutableTransformationWorkspaceProvider.withWorkspace(MutableTransformationWorkspaceServices.java:66)
00:09:49.147		at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
00:09:49.147		at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
00:09:49.147		at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
00:09:49.147		at org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$0(IdentityCacheStep.java:49)
00:09:49.147		at org.gradle.cache.Cache.lambda$get$0(Cache.java:31)
00:09:49.147		at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
00:09:49.147		at org.gradle.cache.ManualEvictionInMemoryCache.get(ManualEvictionInMemoryCache.java:30)
00:09:49.147		at org.gradle.cache.Cache.get(Cache.java:31)
00:09:49.147		at org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$1(IdentityCacheStep.java:47)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$1.lambda$processDeferredOutput$0(DefaultTransformerInvocationFactory.java:153)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory.fireTransformListeners(DefaultTransformerInvocationFactory.java:185)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory.access$000(DefaultTransformerInvocationFactory.java:70)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$1.lambda$processDeferredOutput$1(DefaultTransformerInvocationFactory.java:152)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.CacheableInvocation$3.invoke(CacheableInvocation.java:110)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.CacheableInvocation$1.invoke(CacheableInvocation.java:58)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$TransformPreviousArtifacts$1.lambda$transform$0(TransformationNode.java:305)
00:09:49.147		at org.gradle.internal.Try$Success.flatMap(Try.java:159)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$TransformPreviousArtifacts$1.transform(TransformationNode.java:304)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ArtifactTransformationStepBuildOperation.call(TransformationNode.java:340)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ArtifactTransformationStepBuildOperation.call(TransformationNode.java:319)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
00:09:49.147		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$TransformPreviousArtifacts.calculateValue(TransformationNode.java:301)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$TransformPreviousArtifacts.calculateValue(TransformationNode.java:273)
00:09:49.147		at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:218)
00:09:49.147		at org.gradle.internal.Try.ofFailable(Try.java:41)
00:09:49.147		at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:213)
00:09:49.147		at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:186)
00:09:49.147		at org.gradle.internal.model.CalculatedValueContainer.run(CalculatedValueContainer.java:172)
00:09:49.147		at org.gradle.api.internal.artifacts.transform.TransformationNode.execute(TransformationNode.java:116)
00:09:49.147		at org.gradle.execution.plan.WorkNodeExecutor.execute(WorkNodeExecutor.java:27)
00:09:49.147		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
00:09:49.147		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
00:09:49.147		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
00:09:49.147		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
00:09:49.147		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
00:09:49.147		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
00:09:49.147		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
00:09:49.147		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
00:09:49.147		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
00:09:49.147		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
00:09:49.147		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:09:49.147		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:09:49.147		at java.base/java.lang.Thread.run(Thread.java:829)
00:09:49.147	
```

**Comment by bruno-garcia** [comment]
Thanks for raising. Looks like it's trying to instrument some lib that was proguarded already before it got added. Not sure if it's related.

It seems related to
* https://github.com/getsentry/sentry-android-gradle-plugin/issues/359

And these issues/PRs:
* https://github.com/getsentry/sentry-android-gradle-plugin/issues/304
* https://github.com/getsentry/sentry-android-gradle-plugin/pull/303/

By any chance could you please provide a repro? I imagine it's not related to any of the code in the app, so if just the maven dependencies are known, we possible can repro it.

**Comment by mshafrir-stripe** [comment]
Adding the following resolved the issue. This works for us. Thanks for your help!

```
sentry {
    tracingInstrumentation {
      enabled = false
    }
}
```

**Comment by romtsn** [comment]
Hey @mshafrir-stripe though the issue is resolved fory ou, could you please still run it with `--stracktrace` and post the full stacktrace on this issue? It should give us the library which failed to be instrumented, so we could debug it locally and fix the issue. Thanks!

It sounds like #359 is the same issue, because the failed lib there is the stripe lib as well, so I assume you guys run some proguard/dexguard on your libs?

**Comment by adinauer** [comment]
@mshafrir-stripe we looked into this some more and found out that as soon as "com.stripe:stripeterminal-internal-common:2.12.0" is added to the build, the `ArrayIndexOutOfBoundsException` happens during build.

For `2.12.0` the class causing the issue was `ccc017zz.aaa001 (Ljava/lang/String;)V`.
For `2.10.0` it was `ccc016zz.aaa001 (Ljava/lang/String;)V.`.

This is the code causing the problems in `2.12.0`:

```
package com.stripe.bbpos.bbdevice;
...
final class ccc017zz {
...
   static void aaa001(String s) {
      if (aaa000) {
         Log.d("com.stripe.bbpos", s);
         Calendar var1 = Calendar.getInstance();
         s = "(" + (new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS", Locale.ROOT)).format(var1.getTime()) + ") " + s + "\n";
         String var10 = "log.txt";
         String var2 = Environment.getExternalStorageDirectory().getAbsolutePath() + "/Android/data/com.bbpos.emvswipe.ui/";

         File var10000;
         boolean var10001;
         try {
            var10000 = new File;
         } catch (Exception var9) {
            var10001 = false;
            return;
         }

         File var3;
         File var13 = var3 = var10000;

         boolean var11;
         try {
            var13.<init>(var2);
            var11 = var10000.isDirectory();
         } catch (Exception var8) {
            var10001 = false;
            return;
         }

         if (!var11) {
            try {
               var3.mkdirs();
            } catch (Exception var7) {
               var10001 = false;
               return;
            }
         }

         FileOutputStream var12;
         try {
            var12 = new FileOutputStream;
         } catch (Exception var6) {
            var10001 = false;
            return;
         }

         FileOutputStream var14 = var12;
         FileOutputStream var10002 = var12;
         FileOutputStream var10003 = var12;

         String var15;
         FileOutputStream var10004;
         StringBuilder var10005;
         try {
            var10004 = var10003;
            var15 = s;
            var10005 = new StringBuilder;
         } catch (Exception var5) {
            var10001 = false;
            return;
         }

         StringBuilder var10006 = var10005;

         try {
            var10006.<init>();
            var10004.<init>(var10005.append(var2).append(var10).toString(), true);
            var10002.write(var15.getBytes());
            var14.flush();
            var12.close();
         } catch (Exception var4) {
            var10001 = false;
         }
      }

   }
```

Unfortunately we were unable to detect anything in the `ClassReader` constant pool that would allow us to auto exclude such classes from instrumentation (we use this approach for R8).

Could you please share which obfuscation library (e.g. dexguard) you are using and which version of it?

Also is there anything special in the code you could share so we can reproduce the issue more easily on our side?

Thank you for your help!

Solutions we could look at here could also be:
* Use a regex to exclude classes with certain names
* Hard code an exclusion for the affected package
