### ISSUE TITLE
Stack trace isn't being de-obfuscated for andorid. R8 code shrinker.

### ISSUE THREAD

**Issue by CarsonRedeye** [getsentry/sentry-android-gradle-plugin#4]
Mapping files are uploading correctly via the sentry-gradle-plugin. I can see them under Debug Files in sentry settings. However I can only see a stack trace like this:

`java.lang.NumberFormatException: For input string: "bucket_3017"
    at java.lang.Long.parseLong(Long.java:594)
    at java.lang.Long.parseLong(Long.java:636)
    at c.a.a.e.b0.g.b.a(SourceFile:96)
    at co.redacted.presentation.search.qrcode.b.a(SourceFile:26)
    at co.redacted.presentation.search.qrcode.b.a(SourceFile:3)
    at co.redacted.presentation.search.qrcode.b$g.a(SourceFile:2)
    at co.redacted.presentation.search.qrcode.b$g.a(SourceFile:1)
    at g.b.b0.d.f.onSuccess(SourceFile:2)
    at g.b.b0.e.f.d$a.onSuccess(SourceFile:1)
    at g.b.b0.e.f.e$a.onSuccess(SourceFile:2)
    at g.b.b0.e.f.p$a.onSuccess(SourceFile:1)
    at g.b.b0.e.e.z$a.onComplete(SourceFile:6)
    at n.v.a.a$a.onComplete(SourceFile:2)
    at n.v.a.c.b(SourceFile:9)
    at g.b.m.a(SourceFile:54)
    at n.v.a.a.b(SourceFile:1)
    at g.b.m.a(SourceFile:54)
    at g.b.b0.e.e.z.b(SourceFile:1)
    at g.b.s.a(SourceFile:32)
    at g.b.b0.e.f.p$a.run(SourceFile:1)
    at g.b.r$a.run(SourceFile:2)
    at g.b.b0.g.k.run(SourceFile:2)
    at g.b.b0.g.k.call(SourceFile:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)`

If I download that same mapping file from sentry and use Analyze Stack Track in Android studio, and apply Proguard Unscrambler it works correctly. My suspicion is that changes to the mapping file with new versions of Android Studio/R8 shrinker are causing sentry.io to fail with it's deobfuscation.

I'm using 'io.sentry:sentry-android-gradle-plugin:1.7.21' and 'io.sentry:sentry-android:1.7.21'

**Comment by bruno-garcia** [comment]
What sentry version and SDK, plugin?

**Comment by bruno-garcia** [comment]
I see you wrote the plugin version. Could you please update it to the latest? There are many bug fixes in between the version you are using and latest

**Comment by chpasha** [comment]
I'm using the latest gradle plugin 1.7.30 and the problem still reproducible on sample project (I will attach it here incl. mapping.txt) on self hosted 10.1.0.dev0

the raw exception
```
java.lang.RuntimeException: Test
    at b.b.a.a.a(MyBean.java:1)
    at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:1)
    at b.c.a.a.onClick
    at android.view.View.performClick(View.java:6597)
    at android.view.View.performClickInternal(View.java:6574)
    at android.view.View.access$3100(View.java:778)
    at android.view.View$PerformClick.run(View.java:25885)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

sentry deobfuscation 

```
java.lang.RuntimeException: Test
    at com.example1.domain.MyBean.doWork(MyBean.java:1)
    at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:1)
    at com.exmaple.app.-$$Lambda$ucBvPpMty8S-wiNPHLuaeALrbr0.onClick
    at android.view.View.performClick(View.java:6597)
    at android.view.View.performClickInternal(View.java:6574)
    at android.view.View.access$3100(View.java:778)
    at android.view.View$PerformClick.run(View.java:25885)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

retrace deobfuscation

```
java.lang.RuntimeException: Test
    at com.example1.domain.MyBean.doWork(MyBean.java:16)
    at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:29)
    at b.c.a.a.onClick
    at android.view.View.performClick(View.java:6597)
    at android.view.View.performClickInternal(View.java:6574)
    at android.view.View.access$3100(View.java:778)
    at android.view.View$PerformClick.run(View.java:25885)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

[sentry_my_app.zip](https://github.com/getsentry/sentry-android-gradle-plugin/files/4226259/sentry_my_app.zip)
[mapping.txt](https://github.com/getsentry/sentry-android-gradle-plugin/files/4226263/mapping.txt)

**Comment by chpasha** [comment]
sorry, wrong stacktrace for retrace, here is the correct one - but I think you've got the point

```
java.lang.RuntimeException: Test
        at com.example1.domain.MyBean.doWork(MyBean.java:16)
        at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:29)
        at com.exmaple.app.-$$Lambda$ucBvPpMty8S-wiNPHLuaeALrbr0.onClick(-.java:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by bruno-garcia** [comment]
Thanks a lot for including the mappings and code etc.

Looks like [rust-proguard](https://github.com/getsentry/rust-proguard) is able to find the class `com.exmaple.app.-$$Lambda$ucBvPpMty8S-wiNPHLuaeALrbr0` correctly but not the method `onClick`. But if I read the mapping correctly, it doesn't have a method called `onClick` though:

```
com.exmaple.app.-$$Lambda$ucBvPpMty8S-wiNPHLuaeALrbr0 -> b.c.a.a:
    com.exmaple.app.MainActivity f$0 -> b
```

Looks like a minified method named `b` that maps to a method `f$0` that returns a `com.exmaple.app.MainActivity`

I'm not sure why retrace maps it like that.

The first code from your app that actually matter is the frame `at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:29)` which is correctly demangled.

The frame which Sentry didn't correctly demangle is the generated code done by passing the method as an argument (`button.setOnClickListener(this::buttonClicked);`). Retrace gave it no file name (`-`) and some line number, which isn't much helpful.

In any regard we should figure out a way to demangle the class name there (since `a.a.a.a` is even worse than the generated code purely because it's confusing).

**Comment by marandaneto** [comment]
@chpasha I ran retrace (proguard v6.2.2) and I've got the same stack trace as your first one, which you said it's wrong.

<img width="542" alt="Screenshot 2020-02-20 at 10 24 54" src="https://user-images.githubusercontent.com/5731772/74919852-86028500-53cb-11ea-9959-7f5694b6a60c.png">

What have you changed to demangle the line:
`at com.exmaple.app.-$$Lambda$ucBvPpMty8S-wiNPHLuaeALrbr0.onClick(-.java:2)`
correctly?

@bruno-garcia there's something confusing with the source lines too, look at:

```
at com.example1.domain.MyBean.doWork(MyBean.java:1)
at com.exmaple.app.MainActivity.buttonClicked(MainActivity.java:1)
```

They should not be line `1` but `16` and `29`

**Comment by chpasha** [comment]
>  I've got the same stack trace as your first one, which you said it's wrong.

I'm afraid I've got lost in code variations and stacktraces trying to persuade proguard to obfuscate my simple example. But you've got the point correctly - the problem is wrong line numbers on the very last (or first depending on view) stack frames

**Comment by marandaneto** [comment]
@chpasha perfect, thanks for the explanation, we'll be looking into it.

**Comment by TobiasReich** [comment]
Just for completeness. Our Sentry version is also

`Sentry 10.1.0.dev0842c9c7`

and for the gradle plugin we use

`io.sentry:sentry-android-gradle-plugin:1.7.30`

**Comment by jtsutsui** [comment]
I am also running into the same issue of mismatched line numbers in the Sentry portal. With the same `mapping.txt` file, I ran across 2 different proguard `retrace.jar`. Proguard version 4.7 is giving me the smaller line number while Proguard version 6.2.2 is giving me the correct numbers. Is the sentry portal using an older version of proguard to retrace?

I have Android Studio 3.6 with R8 shrinking.
`io.sentry:sentry-android:2.0.0`
`io.sentry:sentry-android-gradle-plugin:1.7.31`
