### ISSUE TITLE
Build fails because of runtimeConfiguration not being initialised

### ISSUE THREAD

**Issue by StijnAppec** [getsentry/sentry-android-gradle-plugin#530]
### Gradle Version

7.3.3

### AGP Version

7.3.3

### Code Minifier/Optimizer

Proguard

### Version

3.11.1

### Sentry SDK Version

6.26

### Steps to Reproduce

- Gradle sync project with given versions.
- Build the project, but fail to do so.

### Expected Result

Project compiles with sentry installed.

### Actual Result

Gradle build fails with following error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:collectExternalVettsDevDebugDependenciesForSentry'.
> lateinit property runtimeConfiguration has not been initialized

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:collectExternalVettsDevDebugDependenciesForSentry'.
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property runtimeConfiguration has not been initialized
    at io.sentry.android.gradle.tasks.dependencies.SentryExternalDependenciesReportTask.getRuntimeClasspath(SentryExternalDependenciesReportTask.kt:53)
    at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
```

**Comment by romtsn** [comment]
hi @StijnAppec just to make sure - is your Gradle (not AGP) version really 7.3.3 or actually 8.+? I've looked this up and it seems to me this is happening on Gradle 8.+ with configuration cache enabled. Can you confirm that please? Thank you!

**Comment by StijnAppec** [comment]
![Screenshot 2023-07-25 at 15 44 33](https://github.com/getsentry/sentry-android-gradle-plugin/assets/50583205/0f3cd20a-bb07-40a8-bb14-f865b9f2fcb7)

My gradle version is actually 7.3.3. I did note the wrong AGP version, it is 7.2.2 instead of the 7.3.3. But gradle is 7.3.3

**Comment by stefanosiano** [comment]
hi @StijnAppec 
Can you please confirm if you enabled the gradle configuration cache?
