### ISSUE TITLE
Dependencies are not included when using spring-depdency-management 1.1.6

### ISSUE THREAD

**Issue by Alien2150** [getsentry/sentry-android-gradle-plugin#735]
### Gradle Version

8.8

### AGP Version

-

### Code Minifier/Optimizer

None

### Version

4.10.0

### Sentry SDK Version

7.10.0

### Steps to Reproduce

1. Add plugin to build.gradle.kts:
```
id("io.spring.dependency-management") version "1.1.5"
id("io.sentry.jvm.gradle") version "4.10.0"
```
works.

2. Bump spring.dependency-management 
```
id("io.spring.dependency-management") version "1.1.6"
id("io.sentry.jvm.gradle") version "4.10.0"
```

causes compile issues.

### Expected Result

No compile errors

### Actual Result

```
Unresolved reference 'SentryCheckIn'.
Unresolved reference 'spring'.
```

**Comment by romtsn** [comment]
hi @Alien2150 thanks for the report, we'll take a look into this and get back to you!

**Comment by VictorDelCampo** [comment]
Same issue when upgrading the plugin `org.springframework.boot` from 3.3.1 to 3.3.2

**Comment by lbloder** [comment]
Hi @Alien2150,
The fix for this issue was just merged into main and will be available in our next release. 

Can't give you an ETA on that yet though, will coordinate internally and let you know.

@VictorDelCampo Based on my tests, this should also solve the issue with upgrading to 3.3.2.

**Comment by VictorDelCampo** [comment]
@Alien2150 just tested with 4.11.0-alpha.1 and both spring-boot 3.3.2 and io.spring.dependency-management:1.1.6 but same problem:

`	Caused by: java.lang.ClassNotFoundException: io.sentry.logback.SentryAppender
		at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
		at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:103)
		at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
		... 62 more
	Suppressed: ch.qos.logback.core.model.processor.ModelHandlerException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type io.sentry.logback.SentryAppender
		at ch.qos.logback.core.model.processor.AppenderModelHandler.handle(AppenderModelHandler.java:75)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:241)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:216)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:133)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:178)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:123)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:66)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:292)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:254)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:472)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:248)
		... 45 more
	Caused by: [CIRCULAR REFERENCE: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type io.sentry.logback.SentryAppender]`

**Comment by Alien2150** [comment]
> [@Alien2150](https://github.com/Alien2150) just tested with 4.11.0-alpha.1 and both spring-boot 3.3.2 and io.spring.dependency-management:1.1.6 but same problem:
> 
> ` Caused by: java.lang.ClassNotFoundException: io.sentry.logback.SentryAppender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:103) at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56) ... 62 more Suppressed: ch.qos.logback.core.model.processor.ModelHandlerException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type io.sentry.logback.SentryAppender at ch.qos.logback.core.model.processor.AppenderModelHandler.handle(AppenderModelHandler.java:75) at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:241) at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253) at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253) at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90) at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106) at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:216) at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:133) at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:178) at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:123) at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:66) at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:292) at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:254) at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:472) at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:248) ... 45 more Caused by: [CIRCULAR REFERENCE: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type io.sentry.logback.SentryAppender]`

The change is not included in there. @romtsn when can we expect this to be included?

**Comment by romtsn** [comment]
later today or tomorrow we'll make a new release, sorry for the delays!

**Comment by romtsn** [comment]
hey there, apologies for the delays again, but we've finally shipped [4.11.0](https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.11.0) with this fixed included. Please give it a try and let us know if you're still facing issues.
